name: 'composer.lock Diff'
description: 'GitHub Action that diffs composer.lock between current branch and default branch'
branding:
  icon: 'grid'
  color: 'orange'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  dryRun:
    description: Generate the comment contents, but don't make the actual comments, set to "yes" to activate, off by default.
    required: false
    default: 'no'
outputs:
  production:
    description: Changed production dependencies table
  development:
    description: Changed development dependencies table
