name: 'composer.lock Diff'
description: 'GitHub Action that diffs composer.lock between current branch and default branch'
branding:
  icon: 'grid'
  color: 'orange'
inputs:
  dryRun:
    description: Generate the comment contents, but don't make the actual comments, set to "yes" to activate, off by default.
    required: false
    default: 'no'
  workingDirectory:
    description: Directory to execute the diff generator in
    required: false
    default: ''
outputs:
  production:
    description: Changed production dependencies table
  development:
    description: Changed development dependencies table
runs:
  using: "composite"
  steps:
    - name: Poke Pull Request to force Background Process generating a merged_commit_sha
      uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
      id: sha
      with:
        result-encoding: string
        retries: 3
        script: |
          let timeout = 500;
          var pr = (await github.rest.pulls.get({
            pull_number: context.payload.pull_request.number,
            owner: context.payload.repository.owner.login,
            repo: context.payload.repository.name,
          }));
          while (timeout < 60000 && pr.data.merge_commit_sha == null) {
            timeout *= 2;
            await new Promise(r => setTimeout(r, timeout));
            pr = (await github.rest.pulls.get({
              pull_number: context.payload.pull_request.number,
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
            }));
          }
          pr = (await github.rest.pulls.get({
            pull_number: context.payload.pull_request.number,
            owner: context.payload.repository.owner.login,
            repo: context.payload.repository.name,
          }));
          return pr.data.merge_commit_sha;
    #          const requests = Array.from({length: 8}, (v, i) => 500 * Math.pow(2, i)).map(timeout => resolveShaAfterTimeout(timeout));
    #          console.log(requests);
    #          const pr = await Promise.any(requests);
    #          requests.forEach(request => request.cancel());
    #          const resolveShaAfterTimeout = async function (timeout) {
    #            await new Promise(r => setTimeout(r, timeout));
    #            return await github.rest.pulls.get({
    #              pull_number: context.payload.pull_request.number,
    #              owner: context.payload.repository.owner.login,
    #              repo: context.payload.repository.name,
    #            });
    #          };
    - name: Ensure Working Directory has a trailing slash when empty
      uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
      id: workingDirectory
      with:
        result-encoding: string
        retries: 3
        script: |
          const workingDirectory = '${{ inputs.workingDirectory }}';
          if (workingDirectory == '') {
            return workingDirectory;
          } else {
            return workingDirectory.replace(/\/\s*$/, '').concat('/');
          }
    - name: Checkout Head Sha
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      with:
        ref: ${{ steps.sha.outputs.result }}
        fetch-depth: 1
        path: .wyrihaximus-composer.lock-diff/checkout/sha-sha
        sparse-checkout-cone-mode: false
        sparse-checkout: |
          ${{ steps.workingDirectory.outputs.result }}composer.json
          ${{ steps.workingDirectory.outputs.result }}composer.lock
    - name: Checkout Base Ref
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      with:
        ref: ${{ github.event.pull_request.base.ref }}
        fetch-depth: 1
        path: .wyrihaximus-composer.lock-diff/checkout/base-ref
        sparse-checkout-cone-mode: false
        sparse-checkout: |
          ${{ steps.workingDirectory.outputs.result }}composer.json
          ${{ steps.workingDirectory.outputs.result }}composer.lock
    - name: Generate Comments
      uses: docker://ghcr.io/wyrihaximus/github-action-composer.lock-diff:main
      with:
        dryRun: ${{ inputs.dryRun }}
        workingDirectory: ${{ steps.workingDirectory.outputs.result }}
