name: 'composer.lock Diff'
description: 'GitHub Action that diffs composer.lock between current branch and default branch'
branding:
  icon: 'grid'
  color: 'orange'
runs:
  using: 'docker'
  image: 'Dockerfile'
