# syntax=docker/dockerfile:experimental
FROM wyrihaximusnet/php:8.2-nts-alpine-slim-dev-root AS install-dependencies
RUN mkdir /workdir
COPY ./composer.json /workdir
COPY ./composer.lock /workdir
WORKDIR /workdir
RUN composer install --ansi --no-progress --no-interaction --prefer-dist

## Compile runtime image
FROM wyrihaximusnet/php:8.2-nts-alpine-slim-root AS runtime
RUN mkdir /workdir
COPY ./entrypoint.sh ./*.php ./composer.* /workdir/
RUN apk upgrade
COPY --from=install-dependencies /workdir/vendor/ /workdir/vendor/
# hadolint ignore=DL3018
RUN apk add --no-cache jq
ENTRYPOINT ["/workdir/entrypoint.sh"]
