# syntax=docker/dockerfile:experimental
FROM wyrihaximusnet/php:7.4-nts-alpine3.13-slim-dev-root AS install-dependencies
RUN mkdir /workdir
COPY ./composer.json /workdir
COPY ./composer.lock /workdir
WORKDIR /workdir
RUN composer install --ansi --no-progress --no-interaction --prefer-dist

## Compile runtime image
FROM wyrihaximusnet/php:7.4-nts-alpine3.13-slim-root AS runtime
RUN mkdir /workdir
WORKDIR /workdir
COPY ./entrypoint.sh ./composer.* /workdir/
COPY --from=install-dependencies /workdir/vendor/ /workdir/vendor/
RUN ls -lasth ./
ENTRYPOINT ["/workdir/entrypoint.sh"]
